[platform]
os = "linux"
cpu = "x86_64"
min_glibc = "2.34"

[ecc]
github_repo = "openecos-projects/ecc"
asset_name = "ecc-cli-linux-x86_64.tar.gz"
version = "0.1.0-alpha.11"
url = "https://github.com/openecos-projects/ecc/releases/download/v0.1.0-alpha.11/ecc-cli-linux-x86_64.tar.gz"
cnb_url_template = "https://cnb.cool/ecoslab/ecc/-/releases/download/{tag}/{name}"
cnb_url = "https://cnb.cool/ecoslab/ecc/-/releases/download/v0.1.0-alpha.11/ecc-cli-linux-x86_64.tar.gz"
sha256 = "ef34c53631c902bc6f4a99ec08fcaf2a5815e2d59acb68849ce6895c69e08dba"
size = 513992667

[oss_cad_suite]
version = "20260827"
name = "oss-cad-suite-linux-x64-20260827.tgz"
url = "https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2026-08-27/oss-cad-suite-linux-x64-20260827.tgz"
cnb_url = "https://cnb.cool/ecoslab/oss-cad-suite-build/-/releases/download/2026-08-27/oss-cad-suite-linux-x64-20260827.tgz"
sha256 = "c3ffafe1549d5bf321b85e6ac30b3bc6af0af72093d5f45117380bcc0645a8e2"
size = 740836017

[sizer]
github_repo = "openecos-projects/ecc-sizer"
asset_name = "ecc-sizer-0.1.0-alpha-linux-x64.tar.gz"
version = "0.1.0-alpha"
url = "https://github.com/openecos-projects/ecc-sizer/releases/download/v0.1.0-alpha/ecc-sizer-0.1.0-alpha-linux-x64.tar.gz"
sha256 = "d33a2167600711f35fb1dcef55983b0d669176988d8722ed8b22c03471dafee7"
size = 85803792

[pdk]
name = "icsprout55"
version = "v1.10.102"
base_name = "icsprout55-pdk-v1.10.102.tar.gz"
base_url = "https://github.com/openecos-projects/icsprout55-pdk/archive/refs/tags/v1.10.102.tar.gz"
base_sha256 = "68f81ab68ff0e1e7f41ce0c7e1088605f08cd89acdd8dcfd7594b801c98a3074"
base_cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/git/archive/v1.10.102.tar.gz"
base_cnb_sha256 = "9bd412cee21a3b89dad0765723b5d4fba2936c41b1bbea1600eba7ba192221ad"
tech_lef = "prtech/techLEF/N551P6M_ecos.lef"
cell_lefs = [
  "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CR/lef/ics55_LLSC_H7CR_ecos.lef",
  "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CL/lef/ics55_LLSC_H7CL_ecos.lef",
]
liberty_files = [
  "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CH/liberty/ics55_LLSC_H7CH_ss_rcworst_1p08_125_nldm.lib",
  "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CL/liberty/ics55_LLSC_H7CL_ss_rcworst_1p08_125_nldm.lib",
  "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CR/liberty/ics55_LLSC_H7CR_ss_rcworst_1p08_125_nldm.lib",
]

[[pdk.assets]]
name = "ics55_LLSC_H7CH_liberty.tar.bz2"
sha256 = "bb79e74960dec7032295e621933410f51963b9cafbd956a196148d44fe27fb2c"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ics55_LLSC_H7CH_liberty.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ics55_LLSC_H7CH_liberty.tar.bz2"
dest = "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CH/liberty"
size = 76358374
kind = "liberty"

[[pdk.assets]]
name = "ics55_LLSC_H7CL_liberty.tar.bz2"
sha256 = "c2e7a1eea77772582414108fce178a0f444a61bd4e3ce0a2811ef27caa719fa8"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ics55_LLSC_H7CL_liberty.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ics55_LLSC_H7CL_liberty.tar.bz2"
dest = "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CL/liberty"
size = 77546993
kind = "liberty"

[[pdk.assets]]
name = "ics55_LLSC_H7CR_liberty.tar.bz2"
sha256 = "ef33eec4cd5f617d3dd0073122e556df06560dd65eebf805648640038dedc2b7"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ics55_LLSC_H7CR_liberty.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ics55_LLSC_H7CR_liberty.tar.bz2"
dest = "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CR/liberty"
size = 76996026
kind = "liberty"

[[pdk.assets]]
name = "ics55_LLSC_H7CH_gds.tar.bz2"
sha256 = "6268684fdd0784087adc1a972125f9001bc9761c3142ab954d2a9eade53d5490"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ics55_LLSC_H7CH_gds.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ics55_LLSC_H7CH_gds.tar.bz2"
dest = "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CH/gds"
size = 1502685
kind = "gds"

[[pdk.assets]]
name = "ics55_LLSC_H7CL_gds.tar.bz2"
sha256 = "9a643ae864d178f45fec4aa59dc98f0420894760d8a431ce0fd640b97e1c2f68"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ics55_LLSC_H7CL_gds.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ics55_LLSC_H7CL_gds.tar.bz2"
dest = "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CL/gds"
size = 1512316
kind = "gds"

[[pdk.assets]]
name = "ics55_LLSC_H7CR_gds.tar.bz2"
sha256 = "525a7a486e15e36888e4ce08887c946cd16c60dc2c90819fb493d865ed38cc2b"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ics55_LLSC_H7CR_gds.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ics55_LLSC_H7CR_gds.tar.bz2"
dest = "IP/STD_cell/ics55_LLSC_H7C_V1p10C100/ics55_LLSC_H7CR/gds"
size = 1489081
kind = "gds"

[[pdk.assets]]
name = "ICsprout_55LLULP1233_IO_251013_gds.tar.bz2"
sha256 = "47d248be322a6f054a0ab11fe2f2ee83ad76f9ce15d6f4cd53a81c8d08c7693b"
url = "https://github.com/openecos-projects/icsprout55-pdk/releases/download/v1.10.102/ICsprout_55LLULP1233_IO_251013_gds.tar.bz2"
cnb_url = "https://cnb.cool/ecoslab/icsprout55-pdk/-/releases/download/v1.10.102/ICsprout_55LLULP1233_IO_251013_gds.tar.bz2"
dest = "IP/IO/ICsprout_55LLULP1233_IO_251013/gds"
size = 7728902
kind = "gds"
